export { default as About } from './about/About'
export { default as Footer } from './footer/Footer'
export { default as Form } from './form/Form'
export { default as Header } from './header/Header'
export { default as Work } from './work/Work'